### ISSUE TITLE
Add Github data connection

### ISSUE THREAD

**Issue by marcpires** [ecommerce-grpc/services#10]
As a Platform Engineer I want to add the Github Data Connection as a new CRD<br>Then upon configuration it works properly.

<br> Example:

```yaml
apiVersion: connections.devlake.apache.org/v1 # Reflact DevLake API version
kind: Github
metadata:
  name: devlake-dtc-github-grpc-ecommerce
  labels:
    app.kubernetes.io/part-of: devlake
    app.kubernetes.io/managed-by: devlake-operator
    app.kubernetes.io/name: devlake-dtc-github-grpc-ecommerce
  annotations: # TBD
spec:
 type: Cloud # Server
 endpoint: https://api.github.com/ # Default if type is Cloud
 authentication:
  - type: token # app
     value:
     id: # Only if type is App *
     privateKeyRef: # Reference to a Secret *
     installation: # *
  proxy: value #CustomRateLimit
  graphql:
    enabled: true
    requests:
      rate:
        limit: 4501
```

**Definition of Done.**

* Unit tests are created
* e2e tests are created
* Documantation is update
* Use models and client from devlake Terraform provider as base
